language: java
jdk:
- openjdk7
- oraclejdk7
before_script:
- sudo add-apt-repository ppa:eyecreate/haxe -y
- sudo apt-get update
- sudo apt-get install haxe -y
- mkdir ~/haxelib
- haxelib setup ~/haxelib
- haxelib install hxjava
- haxelib git debugger https://github.com/TiVo/debugger.git
- mkdir build
- mkdir report
script: make
deploy:
  provider: releases
  api_key:
    secure: CaN/O5FokNwHm0/1zRit0MfwEvUjsHJtklL0++Z7VaVbh/IXXMuKelfUUXV3ELavS4f4+PMgeagz0DhyK4Hwfwigm2aNAkCI11dDKvE4sEHV/YCQ3BXlFKvvWE6B7ZY+e/BOfAojJ3iI/wZhlOH9Qykvmto7+B6swHXs+4lR2aM=
  file: intellij-haxe.jar
  skip_cleanup: true
  on:
    tags: true
